### ISSUE TITLE
Training of more people to run the bulk user registration script

### ISSUE THREAD

**Issue by knikolla** [nerc-project/coldfront-plugin-api#27]
Currently am the only person with experience in running it. More people should know how so that there isn't any single person bottleneck for the operation.

**Comment by joachimweyl** [comment]
do you have anyone else you wish to train or is this compete?

**Comment by knikolla** [comment]
Since we're not registering any classes any time soon this became lower priority. Once we're closer to the next semester and all outstanding changes to the registration script have merged I will continue with this.

**Comment by knikolla** [comment]
Trained Milson.
