### ISSUE TITLE
Implement filtering in allocations API by attributes

### ISSUE THREAD

**Issue by knikolla** [nerc-project/coldfront-plugin-api#30]
Currently the invoicing tools make an API request to `/api/allocations?all=true`. This responds with ALL the allocations, which doesn't scale.

We need to allow filtering by a specific attribute so that we can search for the allocation that we need.

**Comment by QuanMPhm** [comment]
I would like to implement the use of additional query parameters at the `api/allocations` endpoint. In addition to the `all=true` parameter, I would also like to implement parameters that would filter on an allocation's attributes such as `id=<id>`, `pi=<pi_username>`. The full list of attribute I want to implement so far is:

- allocation id
- allocation's project pi
- allocation's project title
- resource type
- resource name

This can be done by modifying the `get_queryset` function in our `AllocationViewSet` to simply look for additional query parameters. More than one query parameter can be used to filter with conditional ANDs (i.e resource_type=<type>&pi=<pi_username> would filter for both PI name and resource type). Feel free to suggest more attributes that could be filtered.

**Comment by knikolla** [comment]
That seems good, however please be aware of the difference between Allocation attributes (such as `Allocated Project ID`) and something like the allocation's project PI  or project title.

With regards to attributes, such as `Allocated Project ID`, the API plugin doesn't have knowledge about which those attributes are and needs to support a general way to query them.
