### ISSUE TITLE
Return PI email instead of username in /api/allocations

### ISSUE THREAD

**Issue by knikolla** [nerc-project/coldfront-plugin-api#39]
This field is consumed by invoicing scripts and will make our logic for figuring out institutions easier in the short term.

**Comment by QuanMPhm** [comment]
Just to be sure, with this issue I only need to make one change to this one [line](https://github.com/nerc-project/coldfront-plugin-api/blob/2e68d39374168b95b0c5d925ce1ab78d3894f3c8/src/coldfront_plugin_api/serializers.py#L17)?

**Comment by knikolla** [comment]
@QuanMPhm If that's all it takes, yes.
