### ISSUE TITLE
[Epic] API for Users and Allocation Membership

### ISSUE THREAD

**Issue by knikolla** [nerc-project/coldfront-plugin-api#7]
As a ColdFront administrator or PI, I want to be able to manage users and membership to my Resource Allocations through an API.

This will enable [mass subscriptions](https://github.com/OCP-on-NERC/operations/issues/190).

**Comment by knikolla** [comment]
I will prepare a specification to define the API and break it out into chunks for possible delegation of some parts of the work.

**Comment by joachimweyl** [comment]
Replaced with this https://github.com/CCI-MOC/epics/issues/66
